# Generated by Django 6.0.1 on 2026-01-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="myself",
            field=models.TextField(blank=True, null=True, verbose_name="О себе"),
        ),
    ]
