# Generated by Django 6.0.1 on 2026-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_city_user_myself"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nik",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Как вас приветствовать?",
            ),
        ),
    ]
