services:

    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: diplom
        command:
            bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        ports:
            - "8000:8000"
        environment:
            NAME: diplom
            USER: postgres
            PASSWORD: postgres
            HOST: db
            PORT: 5432
        volumes:
            - .:/code
            - static_volume:/code/staticfiles
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:17
        container_name: postgres_db_diplom
        environment:
            POSTGRES_DB: diplom
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
#        ports:
#          - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5


networks:
    app_network:
        driver: bridge
volumes:
    postgres_data:
    static_volume: