# Generated by Django 6.0.1 on 2026-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["date", "contents"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AlterField(
            model_name="record",
            name="contents",
            field=models.TextField(
                help_text="Опишите подробнее, запоминающиеся событие",
                verbose_name="Содержимое",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateField(
                help_text="Введите дату вашего события", verbose_name="Дата записи"
            ),
        ),
    ]
