# Generated by Django 6.0.1 on 2026-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_record_options_alter_record_contents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="contents",
            field=models.TextField(verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateField(verbose_name="Дата записи"),
        ),
    ]
