# Generated by Django 6.0.1 on 2026-01-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_alter_record_contents_alter_record_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["date", "contents"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
